services:
  - type: web
    name: educhat-platform
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
    healthCheckPath: /health
    autoDeploy: false
    disk:
      name: educhat-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1